/**
 * queryValidator.js
 *
 * Validates and auto-corrects a Cube query generated by an LLM.
 *
 * Common LLM mistake: puts a dimension name inside measures[] (or vice versa).
 * Cube.dev throws a hard error for this. Rather than patching the prompt with
 * every possible edge case, this validator cross-references the actual Cube /meta
 * and moves every field to the correct array before the query is sent.
 *
 * Also strips completely unknown fields so Cube gets a clean query.
 */

/**
 * Build fast lookup sets from the filtered Cube meta (the slice already
 * narrowed by DuckDB FTS — same shape as full meta: { cubes: [...] }).
 */
function buildSchemaLookup(cubeMeta) {
  const measures   = new Set();
  const dimensions = new Set();

  for (const cube of (cubeMeta.cubes || [])) {
    for (const m of (cube.measures   || [])) measures.add(m.name);
    for (const d of (cube.dimensions || [])) dimensions.add(d.name);
  }

  return { measures, dimensions };
}

/**
 * Validate and auto-fix a Cube query against the schema.
 *
 * - Field in measures[]   but is actually a dimension → move to dimensions[]
 * - Field in dimensions[] but is actually a measure   → move to measures[]
 * - Completely unknown field → remove with a warning log
 *
 * Returns { fixedQuery, changes } where changes is string[] of corrections made.
 */
function validateAndFixQuery(query, cubeMeta) {
  const { measures, dimensions } = buildSchemaLookup(cubeMeta);
  const changes = [];

  const outMeasures   = [];
  const outDimensions = [...(query.dimensions || [])];

  // --- Validate measures[] ---
  for (const field of (query.measures || [])) {
    if (measures.has(field)) {
      outMeasures.push(field);
    } else if (dimensions.has(field)) {
      if (!outDimensions.includes(field)) outDimensions.push(field);
      changes.push(`moved "${field}" from measures[] → dimensions[] (it is a dimension)`);
    } else {
      changes.push(`removed unknown field "${field}" from measures[]`);
    }
  }

  // --- Validate dimensions[] ---
  const correctedDimensions = [];
  for (const field of outDimensions) {
    if (dimensions.has(field)) {
      correctedDimensions.push(field);
    } else if (measures.has(field)) {
      if (!outMeasures.includes(field)) outMeasures.push(field);
      changes.push(`moved "${field}" from dimensions[] → measures[] (it is a measure)`);
    } else {
      changes.push(`removed unknown field "${field}" from dimensions[]`);
    }
  }

  // --- Strip invalid top-level keys ---
  // Cube only accepts these keys; anything else (e.g. "joins") causes a hard error.
  const ALLOWED_KEYS = new Set([
    "measures", "dimensions", "timeDimensions", "filters",
    "order", "limit", "segments", "timezone", "renewQuery", "ungrouped"
  ]);
  const fixedQuery = { measures: outMeasures, dimensions: correctedDimensions };
  for (const key of Object.keys(query)) {
    if (key === "measures" || key === "dimensions") continue; // already handled
    if (ALLOWED_KEYS.has(key)) {
      fixedQuery[key] = query[key];
    } else {
      changes.push(`removed invalid top-level key "${key}" (not a valid Cube query field)`);
    }
  }

  // Clean up empty arrays — Cube prefers them absent
  if (fixedQuery.measures.length   === 0) delete fixedQuery.measures;
  if (fixedQuery.dimensions.length === 0) delete fixedQuery.dimensions;

  if (changes.length > 0) {
    console.log("[queryValidator] Auto-corrected:", changes);
  }

  return { fixedQuery, changes };
}

module.exports = { validateAndFixQuery };
